/**
 * conjoon
 * conjoon.github.io
 * Copyright (C) 2022 Thorsten Suckow-Homberg https://github.com/conjoon/conjoon.github.io
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge,
 * publish, distribute, sublicense, and/or sell copies of the Software,
 * and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE
 * USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    docs: [
        "introduction",
        {
            type: "category",
            label: "Getting Started",
            link: {
                type: "generated-index"
            },
            collapsed: false,
            items: [
                "installation",
                "configuration"
            ]
        },
        /**
         * +---------------------------
         * |       FRONTEND GUIDE
         * +---------------------------
         */
        {
            type: "category",
            label: "Frontend Guide",
            collapsed: false,
            link: {type: "doc", id: "frontend"},
            items: [{
                type: "category",
                collapsed: true,
                label: "extjs-app-imapuser",
                link: {type: "doc", id: "extjs-app-imapuser/extjs-app-imapuser"},
                items: [{
                    type: "autogenerated",
                    dirName: "extjs-app-imapuser/docs"
                }]
            }, {
                type: "category",
                collapsed: true,
                label: "extjs-app-webmail",
                link: {type: "doc", id: "extjs-app-webmail/extjs-app-webmail"},
                items: [{
                    type: "autogenerated",
                    dirName: "extjs-app-webmail/docs"
                }]
            }]
        },
        /**
         * +---------------------------
         * |       BACKEND GUIDE
         * +---------------------------
         */
        {
            type: "category",
            label: "Backend Guide",
            link: {type: "doc", id: "backend"},
            collapsed: false,
            items: [{
                type: "category",
                collapsed: true,
                label: "lumen-app-email",
                link: {type: "doc", id: "lumen-app-email/lumen-app-email"},
                items: [{
                    type: "autogenerated",
                    dirName: "lumen-app-email/docs"
                }]
            }]
        },
        "REST API"
    ]
};

module.exports = sidebars;
